### ISSUE TITLE
Export Sheet Data not working today

### ISSUE THREAD

**Issue by RalfProtecky** [Synthoid/ExportSheetData#109]
Hey, I've noticed that Export Sheet Data hasn't been working today. Is this a global problem?

**Comment by Synthoid** [comment]
Well two people commenting about problems exporting within minutes of each other is probably not a good sign. (Though I am excited that enough people are using ESD for two people to comment on this at once). I just tried exporting simple JSON and XML files and that seems to work fine for me (tested on a G Suite account). Can you link an example for your sheet?

**Comment by RalfProtecky** [comment]
There's no error for me. I've always used a compiler that created a json for me - right now it's getting stuck at loading without any error, nor response - it just loads (the circle is going). Even left it for about 30 minutes, nothing happened. 

Right now I'm using workaround by clicking "Visualize" and just copying the text.

**Comment by matt-wadsworth** [comment]
Following on from my comment in the other issue thread; happy to report exporting seems to be working as usual now for our team, unsure what was causing the issue earlier today.

I did "reset" the sharing settings on one of the sheets affected, not sure if that made any difference.

**Comment by RalfProtecky** [comment]
Happy to confirm that it indeed works! Thanks mate.

**Comment by Synthoid** [comment]
Glad everything seems to be working now! Not sure what was happening, though I was noticing a lot of extra logs showing up in the developer console that make me a little uncomfortable. I’ll do some research to see if I can clean those up, but for now I’m closing this issue.
