### ISSUE TITLE
drive.google.com refused to connect. error message

### ISSUE THREAD

**Issue by RezaRahmati** [Synthoid/ExportSheetData#116]
Hi there

I installed the addon (v59), and gave the permission when I was installing, but when I open sidebar or any other related forms I get the error

`drive.google.com refused to connect.`

![image](https://user-images.githubusercontent.com/10086092/84351381-4681c380-ab89-11ea-983f-3f5ad7f2e962.png)

**Comment by Synthoid** [comment]
That’s a new one. My initial guess would be that it was a connection problem for some reason. Are you still having this issue? If so, do you have multiple accounts signed in?

**Comment by RezaRahmati** [comment]
I still have same issue,
Yes I have multiple accounts signed in, and I only install and gave access to the account that has the file, and currently opening the file by that account (for other accounts it doesn't show the addon at all)

**Comment by Synthoid** [comment]
Can you try logging out of all but one account? For some reason, multiple accounts being signed in occasionally messes with some add-one.

**Comment by RezaRahmati** [comment]
yes, I logged-in cognito mode and issue reslolved
