### ISSUE TITLE
Only exports the last row of my sheet?

### ISSUE THREAD

**Issue by rowe-morehouse** [Synthoid/ExportSheetData#117]
Cool add-on, thanks for making this. 

Trying to export to JSON, and your add-on formats it how I want it, but it **only exports the last row** in the sheet?

settings: JSON, Current Sheet, Nested Elements

Here is the sheet:

https://docs.google.com/spreadsheets/d/1IM-0ouC3-t3QbeCh2iBJW6fhSbLNLdCgAWe5kMauLIg/edit?usp=sharing

I read all the docs, but still no clue what I am doing wrong! thank you for having a look.

**Comment by Synthoid** [comment]
I duplicated your inital tab and added the `NA_` prefix to its name. If you visualize the data does it look like what you need?

The issue you are seeing is a common one with Nested Elements. Basically each row of the sheet is overwriting the previous row due to key formatting issues.

**Comment by rowe-morehouse** [comment]
Nice one! … you just made my day a lot better! thank you.

**Comment by Synthoid** [comment]
Glad I could help!
