### ISSUE TITLE
Ignore multiple prefix

### ISSUE THREAD

**Issue by Alan3k** [Synthoid/ExportSheetData#118]
Hi,

I couldn't find solution.

How can I add more than one "Ignore prefix"?

I would like to ignore more than one column on export.

I have tired like this:

id, title, content
id; title; content
id|title|content

..and it didn't worked.

Sorry for my english and thanks for help.

**Comment by Synthoid** [comment]
To ignore multiple columns, you just need to add the ignore prefix to each column's key:


Name | HP | NOEX_MP | STR | CHR | INT | Special | NOEX_Notes
-- | -- | -- | -- | -- | -- | -- | --
Gorgon | 64 | 50 | 13 | 15 | 14 | 10% chance to petrify. | https://en.wikipedia.org/wiki/Gorgon

Default output:
```
{
  "Monsters": {
    "Gorgon": {
      "HP": 64,
      "NOEX_MP": 50,
      "STR": 13,
      "CHR": 15,
      "INT": 14,
      "Special": "10% chance to petrify.",
      "NOEX_Notes": "https://en.wikipedia.org/wiki/Gorgon"
    }
  }
}
```

Ignore Prefix output:
```
{
  "Monsters": {
    "Gorgon": {
      "HP": 64,
      "STR": 13,
      "CHR": 15,
      "INT": 14,
      "Special": "10% chance to petrify."
    }
  }
}
```
