### ISSUE TITLE
sidebar fails to open in v60

### ISSUE THREAD

**Issue by epoger** [Synthoid/ExportSheetData#122]
Everything was working fine for me as of Aug 28... but today, when I try to open the Export Sheet Data sidebar (on certain spreadsheets), the sidebar is blank inside.  (see screenshot)
![image](https://user-images.githubusercontent.com/14200833/91752647-ac805480-eb94-11ea-9067-fb44d8da1a97.png)

It seems like the add-on was updated from v59 to v60 since Aug 28, so I am guessing it's something with this version update...

I have seen this on some spreadsheets but not all of them... I have not yet figured out what exactly causes it to fail.

Google Chrome | 84.0.4147.135 (Official Build) (64-bit)
-- | --
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS | OS X Version 10.10.5 (Build 14F2511)
JavaScript | V8 8.4.371.23
Flash | 32.0.0.414 /Users/epoger/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.414/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --origin-trial-disabled-features=MeasureMemory

**Comment by epoger** [comment]
Here are some error messages I see in the Javascript console when opening the sidebar:

Jo {message: "There was an error during the transport or process…this request. Error code = 10, Path = /wardeninit", name: "TransportError", stack: "TransportError: There was an error during the tran…/js/4285718584-warden_bin_i18n_warden.js:194:247)"}message: "There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit"name: "TransportError"stack: "TransportError: There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit↵    at new Jo (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:194:334)↵    at Oo.v.ad (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:202:350)↵    at Qi (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:89:228)↵    at Pi (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:86:472)↵    at Li.D (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:86:419)↵    at Qi (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:89:228)↵    at Pi (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:86:472)↵    at Oo.<anonymous> (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:201:159)↵    at tn (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:158:304)↵    at wo (https://docs.google.com/static/macros/client/js/4285718584-warden_bin_i18n_warden.js:194:247)"__proto__: B
4285718584-warden_bin_i18n_warden.js:68 Net state changed from IDLE to BUSY
4285718584-warden_bin_i18n_warden.js:68 Net state changed from BUSY to IDLE
2495449455-mae_html_user_bin_i18n_mae_html_user.js:56 Uncaught  at getExportProperties (ExportSheetData:48)

ue @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:56
wf @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:70
(anonymous) @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:11
ig.K @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:97
de @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:49
$d @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:50
Yd.b @ 2495449455-mae_html_user_bin_i18n_mae_html_user.js:46

**Comment by Synthoid** [comment]
Hmm... Are you signed into multiple accounts?

**Comment by epoger** [comment]
Yes, definitely signed into multiple accounts.  Seems like I am having this problem more with my company work (Google Apps for Domain), less with spreadsheets opened with my gmail account.  But that could just be because the spreadsheets at work are bigger!

**Comment by Synthoid** [comment]
Can you sign out of all but your primary account? There's a known bug with add-ons involving multiple accounts being signed in and I'm betting that is the problem.

You can see more info about the bug here: https://sites.google.com/site/scriptsexamples/home/announcements/multiple-accounts-issue-with-google-apps-script

**Comment by henriquebf** [comment]
> Can you sign out of all but your primary account? There's a known bug with add-ons involving multiple accounts being signed in and I'm betting that is the problem.

I experienced same issue and by having just one account connected it seems to work.

**Comment by epoger** [comment]
I opened up a browser I don't usually use (Firefox 78.1.0esr), where I am not signed into any Google accounts, and tried the following (which I will call "ATTEMPT 1"):

- Went to www.google.com.  Confirmed that I am not signed into any Google accounts. Signed into my work Google account.
- Opened a Google Sheet from work.
- Add-ons > Export Sheet Data (v60) > Open Sidebar ... it works fine.
- Closed the Google Sheet.
- Went to www.google.com and signed into my personal Gmail account (but my work Google account is still signed in as well, and marked "Default")
- Opened that same Google Sheet from work.  The Google ID photo at top right indicates that it has automatically switched to my work persona.
- Add-ons > Export Sheet Data > Open Sidebar ... it still works.
- Closed the Google Sheet.
- Went to www.google.com and signed out of all accounts.

Then tried ATTEMPT 2:

- Went to www.google.com.  Confirmed that I am not signed into any Google accounts. Signed into my **personal** Google account.
- Attempted to open a Google Sheet from work, but I didn't have access (because I am signed into my personal account instead).
- Went to www.google.com and signed into my work Gmail account (but my personal Google account is still signed in as well, and marked "Default")
- Opened that same Google Sheet from work. 
- Add-ons > Export Sheet Data > Open Sidebar ... it fails (the sidebar remains blank).
- In the Web Console, I see this error: "Uncaught ScriptError: Exception: No item with the given ID could be found. Possibly because you have not edited this item or you do not have permission to access it."
- Closed the Google Sheet.
- Went to www.google.com and signed out of all accounts.

CONCLUSION: 
It is indeed a matter of being signed into multiple Google accounts, **similar** to what is described in https://sites.google.com/site/scriptsexamples/home/announcements/multiple-accounts-issue-with-google-apps-script , but with these caveats:
- The issue described there supposedly only happens if you are logged in with multiple accounts of the *same domain name* (which I am not).
- Given that I have always been signed in this way, and never before encountered this problem, I still suspect there is something in v60 which may have exposed this underlying problem.

At any rate, I have my workaround.  Thanks to all.

**Comment by Synthoid** [comment]
Unfortunately this is a sprawling bug created by the add-on backend so only Google can actually fix it. It's even more frustrating because it can work for months only to randomly fail, like you experienced. In any case, glad the issue was resolved!
