### ISSUE TITLE
Sidebar appearing blank

### ISSUE THREAD

**Issue by llancaster17** [Synthoid/ExportSheetData#123]
I have a spreadsheet that I had the JSON export functionality working great on my personal google account. I then made a copy of that sheet in my organizational account and it worked on July 9. I revisited on 9/17 and when I go to open the sidebar it appears blank. I uninstalled and re-installed on an organizational level, but the issue still occurs.

**Comment by Synthoid** [comment]
Do you have multiple accounts signed in?

**Comment by llancaster17** [comment]
I do. Yes.

**Comment by Synthoid** [comment]
If you sign out of all but one and try opening the sidebar, does it work as expected?

**Comment by Synthoid** [comment]
Closing this issue for now as multiple accounts were probably the issue here.
