### ISSUE TITLE
Nesting?

### ISSUE THREAD

**Issue by handes2355** [Synthoid/ExportSheetData#138]
I'm trying to create this format:

    {
        name: "Interaction",
        userSays: [
            "Hello",
            "Hi"
        ],
        responses: [
            {
                type: "text",
                elements: ["Hi, how are you", "Hello! What can I do for you?"]
            }
        ]
    }

This is my sheet

https://docs.google.com/spreadsheets/d/1egdQFcCgXPa-iSvcQYzuDBqWXmDhYgmov5NiLDqMwm4/edit?usp=sharing

**Comment by Synthoid** [comment]
I think I have what you are looking for:

```json
{
  "Sheet1": [
    {
      "name": "Interaction",
      "userSays": [
        "Hello",
        "Hi"
      ],
      "responses": [
        {
          "type": "text",
          "elements": [
            "Hi",
            "how are you",
            "Hello! What can I do for you?"
          ]
        }
      ]
    },
    {
      "name": "Secon Interaction",
      "userSays": [
        "one",
        "two",
        "three"
      ],
      "responses": [
        {
          "type": "text",
          "elements": [
            "four",
            "five",
            "six"
          ]
        }
      ]
    }
  ]
}
```

I got that with the following sheet:

**Sheet name: `NA_Sheet1`**

name | JA_userSays | [responses]{#type} | [responses]{#type}JA_elements
-- | -- | -- | --
Interaction | Hello, Hi | text | Hi, how are you, Hello! What can I do for you?
Secon Interaction | one, two, three | text | four, five, six

With Nested Elements, Array Prefix, and Nested Array Prefix enabled.

**Comment by handes2355** [comment]
Thanks for taking a look.  I'm getting this error message

TypeError: Cannot set property 'elements' of undefined
    at exportSpreadsheetJson (ExportSheetData:1802:58)
    at exportJson (ExportSheetData:889:5)
    at __GS_INTERNAL_top_function_call__.gs:1:8

https://docs.google.com/spreadsheets/d/1egdQFcCgXPa-iSvcQYzuDBqWXmDhYgmov5NiLDqMwm4/edit?usp=sharing

**Comment by Synthoid** [comment]
Looks like the keys are missing the `#`. Your key path should be:

`[responses]{#type}`

Not:

`[responses]{type}`

**Comment by handes2355** [comment]
Thak you - that was it.  Appreciate the assist
