### ISSUE TITLE
(Bug) Export configuration are erased after clicking Visualize before the complete loading of the Sidebar

### ISSUE THREAD

**Issue by sgaumin** [Synthoid/ExportSheetData#139]
**Describe the bug**
After choosing the option Export Sheet Data/Open Sidebar. Before the sidebar is completely loaded, if we click on the Visualize button, the settings saved on the Sidebar are erased.

**To Reproduce**
1. Click on Export Sheet Data/Open Sidebar
2. Once the Visualize button is visible click on it
3. The sidebar should be empty of settings, instead of reusing the last configuration

**Expected behavior**
Maybe the Visualize button should be displayed once sidebar is completely loaded.

**Comment by Synthoid** [comment]
Not a bad idea. I'll look into making those buttons non-interactive until the load operation finishes.

**Comment by Synthoid** [comment]
This has been implemented and will be available in the next version of ESD (v66)
