### ISSUE TITLE
Generates invalid XML names

### ISSUE THREAD

**Issue by michaelhkay** [Synthoid/ExportSheetData#15]
As far as I can see the tool make no attempt to ensure that the XML element names generated are valid names. In fact, it goes about it completely the wrong way: it formats names using a routine formatXmlString which converts `<` to `&lt;`, etc, despite the fact that entity references are not allowed in names. I'm seeing XML in which the element names are numeric (`<1>`) or contain spaces (`<birth date>`.

**Comment by Synthoid** [comment]
One of my goals was to avoid altering user data on export as much as possible, but I can see the benefits of auto formatting names so they can look nice in the spreadsheet, but function properly in the export.

**Comment by Synthoid** [comment]
I've just pushed a new version (v34) that should automatically format element names so that they conform to XML standards. Feel free to inform me of any extra formatting you can think of.
