### ISSUE TITLE
Does not work in Chrome

### ISSUE THREAD

**Issue by krtkv** [Synthoid/ExportSheetData#152]
Chrome Version 96.0.4664.110 (Official Build) (64-bit)

The extension does not work in any case. I am unable to load or import settings. Sidebar opens, but Export button does nothing, even with the default settings.

Please fix it, thanks

**Comment by Synthoid** [comment]
This sounds like the [multiple account issue](https://github.com/Synthoid/ExportSheetData/blob/master/docs/troubleshooting.md). This is a google side issue that I haven't found a great solution for, so the best way to fix it currently is to sign out of all but one account then open the ESD sidebar.

**Comment by krtkv** [comment]
@Synthoid Thanks, now it works.

**Comment by Synthoid** [comment]
Glad to hear it. That bug has been around for a while and there's not a great way for me to address it unfortunately. Super frustrating.
