### ISSUE TITLE
(Bug) Exporting an array bugged while including a period and negatives

### ISSUE THREAD

**Issue by AreliusIS** [Synthoid/ExportSheetData#154]
I'm trying to export x.y coordinates.
The formatting after visualization seems bugged.

![image](https://user-images.githubusercontent.com/107047400/195054818-9fdbb589-a5ee-4655-96a5-a8ba0e534599.png)
![image](https://user-images.githubusercontent.com/107047400/195054945-5b1a4e66-a739-496e-a178-9d94b1d409fa.png)

**Comment by Synthoid** [comment]
Sorry for the delayed response. This is because `-1.-1`  is not a valid number. `-1.1` would be valid though.
