### ISSUE TITLE
Cell array incorrectly coercing strings to numbers in JSON output

### ISSUE THREAD

**Issue by stuffisthings** [Synthoid/ExportSheetData#159]
**Describe the bug**
I have array cells in my document that can contain a mix of values like `6` or `"6-7"`. I want the numbers to be treated as numbers and the others to be treated as strings. But values like `"6-7"` are coerced to `6` in the output. This is true even in arrays that are all string values like `"6-7"/"6-7"/"6-7"` (`/` is my seperator here).

**To Reproduce**
1. Create a cell with value `"6-7"/"6-7"/"6-7"`
2. Name the column `JA_foo`
3. Options: Array prefix: "JA_", Array seperator: "/", Export contents as array
4. JSON output will be rendered as `[ { "foo": [ 6, 6, 6 ] } ]`

**Expected behavior**
JSON output sould be `[ { "foo": [ "6-7", "6-7", "6-7" ] } ]`

**Screenshots**

Here's some test cases against the actual output:
![image](https://github.com/Synthoid/ExportSheetData/assets/6656179/cc965c9b-acab-4dc0-a23d-fc2cbb23b456)
```
[
  {
    "foo": [
      6,
      6,
      6,
      6
    ]
  },
  {
    "foo": [
      "Thing",
      "Thing",
      "Thing"
    ]
  },
  {
    "foo": [
      "One-2",
      "One-3"
    ]
  },
  {
    "foo": [
      "2-One",
      "3-One"
    ]
  },
  {
    "foo": [
      6,
      9
    ]
  },
  {
    "foo": [
      6,
      6,
      6
    ]
  }
]
```

**Info (please complete the following information):**
 - Browser: Chrome
 - Do you have multiple accounts signed in? No

**Possible solution**

My guess would be it has something to do with use of `parseFloat` in `getCellContentArray` (because `parseFloat('6-7') === 6`).

I could try to do a PR at some point but what I've done to deal with similar situations in the past is check the length of `parseFloat(val)` against the length of `val` and if they are different treat `val` as a string -- not sure that is totally robust though.

**Comment by Synthoid** [comment]
This will be fixed in v67. The issue was indeed because `parseFloat("6-7")` evaluates to `6`, as you said. Stupid JS and it trying to make every situation work.

Cell arrays now have a more explicit `isNumber(value)` check that manually checks if a "parsable" number is indeed a valid number. For example, given the value "six, 6, 6-7":

Version | Output
-------- | --------
Current | `[ "six", 6, "6-7" ]`
Previous | `[ "six", 6, 6 ]`
