### ISSUE TITLE
ESD is offline / Google Docs encountered an error

### ISSUE THREAD

**Issue by thoughtden** [Synthoid/ExportSheetData#161]
**Describe the bug**
When opening ESD sidebar, continually getting error from Google: "Google Docs encountered an error. Please try reloading this page, or coming back to it in a few minutes."

**To Reproduce**
1. Open a new spreadsheet
2. Extensions > Export Sheet Data > Open Sidebar
3. See error

**Expected behavior**
Would expect sidebar to open. Occasionally it does open, but any attempt to export the JSON results in the same error

**Screenshots**
Screenshots attached

**Info (please complete the following information):**
 - Chrome Version 122.0.6261.69 (Official Build) (arm64)
 - MacBook 2021 M1 pro, Ventura 13.3.1 (22E261)
 - Multiple accounts have profiles on this laptop

**Additional context**
- Attempted to reinstall - failed
- Cleared cache - failed
- Tried on multiple different laptops (Mac and PC) - failed

<img width="662" alt="Screenshot 2024-02-26 at 09 21 37" src="https://github.com/Synthoid/ExportSheetData/assets/81439909/36c981ea-6a98-4d98-b9d9-722cd87ec986">

**Comment by thoughtden** [comment]
Sorry, I now see this is a known issue linked to having multiple accounts signed in. I've found a workaround

**Comment by Synthoid** [comment]
Sorry Google's support for multiple accounts is so buggy. I have never found a good work around for the issue unfortunately.
