### ISSUE TITLE
application has been blocked

### ISSUE THREAD

**Issue by Lklklklk1** [Synthoid/ExportSheetData#164]
![Screenshot (67)](https://github.com/Synthoid/ExportSheetData/assets/155923329/6c76820f-8e81-4be9-8b09-06a465c17e6c)

**Comment by alireza-s13** [comment]
I have such a problem.

**Comment by Synthoid** [comment]
Currently working on a fix for this, should be resolved soon hopefully. Closing this issue since it is a duplicate of an exiting issue that can be found [here](https://github.com/Synthoid/ExportSheetData/issues/163).
