### ISSUE TITLE
Tag non-exportable columns

### ISSUE THREAD

**Issue by jeauger** [Synthoid/ExportSheetData#17]
We should be able to tag the columns we don't want to export. For exemple we can add the string [NOEXPORT] in the column title.

**Comment by Synthoid** [comment]
Currently, you can leave a key field blank and it will be ignored when exporting. But you are right that it would be convenient to also have a prefix that can flag a column to be ignored, similar to how other settings can be set per column via key prefix.

**Comment by Synthoid** [comment]
Just pushed a new version (v35) that supports this.
