### ISSUE TITLE
Convert text format to html tag

### ISSUE THREAD

**Issue by loudoweb** [Synthoid/ExportSheetData#18]
It would be great to export a formatted text like the following: 

My text contains a **bold** word.

to:

My text contains a `<b>`bold`</b>` word or My text contains a `<strong>`bold`</strong>` word

Of course, when exporting to xml, it means that we should only propose this option when the option "Export columns as child elements" is checked to keep xml valid and add `<![CDATA[]]>` like this:
`<![CDATA[My text contains a <b>bold</b> word]]>`

Please consider this feature. Thanks for your addon.

**Comment by Synthoid** [comment]
Interesting idea. I've not tried to parse Google Sheets formatting before, so I'm not 100% sure this is easily possible, but I will definitely take a look.

**Comment by loudoweb** [comment]
Hi,

I've opened a [question on stackoverflow](http://stackoverflow.com/questions/41899116/how-to-convert-formatted-text-to-html-tag-in-google-apps-script). For now, I'm unsure this is possible :/

**Comment by loudoweb** [comment]
I've opened a [feature request](https://code.google.com/p/google-apps-script-issues/issues/detail?id=6669&colspec=Stars%20Opened%20ID%20Type%20Status%20Summary%20Component%20Owner) on Google apps script because it seems that we can't know precisely the format of the cell. Please vote.

**Comment by Synthoid** [comment]
Closing this issue as it cannot currently be accomplished with existing sheet functionality. If this becomes exposed later, I’ll take a crack at it.
