### ISSUE TITLE
(JSON / XML) Time values are not formatted properly when exporting

### ISSUE THREAD

**Issue by Synthoid** [Synthoid/ExportSheetData#2]
Because of how Google Sheets stores time based data, time values are formatted strangely when exporting. Should format in a more expected and readable way.

**Comment by Synthoid** [comment]
After doing some research on this, it seems that the date value returned for time entries is formatted as either a [JSON date](https://www.w3schools.com/jsref/jsref_tojson.asp) or a [UTCString](https://www.w3schools.com/jsref/jsref_toutcstring.asp). So while the values are not the most human readable, they do have a standard format.

This means I'll need to think about what options people would want these values to be formatted with. These options would likely be:

- DateTime (current export format)
- Time (11:00 PM, 23:00)
- Date (1/01/2001)
- Longform Date (January 1, 2001)

**Comment by cgaray007** [comment]
Is it posible to read the format according to how the user defined it on the spreadsheet? for instance: "YYY-MM-DD"

**Comment by Synthoid** [comment]
Ideally, it would just match the visible format shown in the sheet. Like I mentioned above, date/time values are stored in a longform format that is then validated to display a specific way in the sheet.  As a side note, this means that time values like `11:00 AM` are actually coded to represent `11:00 AM January 1, 1900` (pretty sure its 1900 anyway).

To answer your question though, I could add an option for a Year-Month-Day format. If I can figure out a way to parse what format was being displayed, I'll try to use that. Otherwise, allowing the user to select the date/time format may be the best I can do. Hopefully it doesn't come to that since that would be a mountain of work to write and maintain.

**Comment by OhNoxius** [comment]
Before making a new post, I want to see if this issue is still being worked on? A custom date format on export would be great (ideally the same formatting as used in the sheet), but I also have an issue with the timezone. For example:

> _1977-07-**16**_ in my sheet becomes _Fri Jul **15** 1977 18:00:00 GMT-0400 (EDT)_ in the xml

I'm using XSLT 1.0 to display this date, and I can parse to a proper format, but I can't change the timezone and display the correct date...

In my Google sheet settings I have set _locale: United States_ (because there is no option for Belgium) and _Time zone: GMT +01:00 Brussels_.

Btw great add-on, it's a lifesaver for me!

**Comment by Synthoid** [comment]
Thanks for using ESD, and glad to hear you are enjoying it!

Date formatting is still on the roadmap, but my output has slowed because of my recent work schedule. Apologies for the delay. With regards to the timezone, I'm guessing that time value is actually determined by the server processing the script? Add-ons are processed server side, not client side, so it's conceivable that the time difference is due to server location, though that does seem unlikely given the amount of servers Google has all over the place.

I'm hoping I can tell what time zone the user is in so I don't have to include a field for timezone selection then manually adjust the date value.

Anyway, current design plan is to provide a dropdown with some preset formats and a custom option that would allow users to specify a format using keywords. For example (each line is a different custom format):

```
YEAR-MONTH-DAY
MONTH, DAY, DAY_NAME
DAY_SHORTNAME MONTH_NAME, DAY, TIME
```

Would export as:

```
2019-07-01
07, 01, Monday
Mon July, 01, 7:00 PM
```

Unfortunately, the time value seen in the sheet is not how the time value is exported when retrieving the data from the cell, so Sheets is converting that to one of the two supported datetime formats automatically, before I can get to it. Obviously, I'd prefer to just use the formatting visible in the sheet, but that can only happen currently if the user manually tells sheets to not format date cells as dates.

**Comment by Synthoid** [comment]
v67 will support customizing date-time formats.
