### ISSUE TITLE
Sheet title no longer exporting in XML

### ISSUE THREAD

**Issue by An0nx** [Synthoid/ExportSheetData#21]
Previously this app would export the XML file with the following format:

```
<rootElement>

    <sheetTitle>

        <element>

        </element>

    </sheetTitle>

</rootElement>
```

Now the app skips appending the sheet title, why is this?

**Comment by Synthoid** [comment]
The previous format was actually an oversight with XML exporting. Using "Current sheet only" will unwrap the current sheet as there would be an unneeded extra layer to the exported data. If you would like the sheet's name as an extra wrapping element, you can use the "Custom" option and select only the sheet you desire to export. That should give you the formatting you are looking for.

**Comment by An0nx** [comment]
Perfect, thanks for your help!
