### ISSUE TITLE
Improper closure of last element if next columns are to be ignored.

### ISSUE THREAD

**Issue by DavidFickes** [Synthoid/ExportSheetData#23]
If you have a sheet in which the last element that you want to include in the .json is followed by "ignored" columns, the export appends a comma at the last element before the closing brace.  Seems to be an issue of not checking to make sure there is another active column to be included ...

Not a big deal but most of my sheets will use the far right for index columns if needed.  The quick fix is to put a live column on the far right but this is not ideal.

### Current: 
{
  "NEW01" : {
    "TestRecord" : "MAJ WI  NEW01",
    "NumberOfInverters" : "1",
  },
  "NEW02" : {
     _... and so forth ...._ 

### Ideal:
{
  "NEW01" : {
    "TestRecord" : "MAJ WI  NEW01",
    "NumberOfInverters" : "1"
  },
  "NEW02" : {
 _... and so forth ...._

**Comment by Synthoid** [comment]
I just pushed a new version that should address this issue. Thanks for pointing it out!

**Comment by Synthoid** [comment]
Just tested a little more, and the current check will still append a trailing comma if multiple columns are ignored at the end of a row.

**Comment by Synthoid** [comment]
This is now fixed as of V40.
