### ISSUE TITLE
(JSON / XML) Save / Load export settings

### ISSUE THREAD

**Issue by Synthoid** [Synthoid/ExportSheetData#25]
Allow formatting settings to be exported and loaded, either by file or copy paste into a settings field of some kind.

**Comment by grossima** [comment]
Should be very useful for etl batch purposes, when the same sheets have to be exported continuously.

**Comment by Synthoid** [comment]
It would be preferable to auto save settings inside the document in addition to being able to export settings.

**Comment by Synthoid** [comment]
V38 has the first implementation of this feature.
