### ISSUE TITLE
(General) 'Replace existing file' options

### ISSUE THREAD

**Issue by Synthoid** [Synthoid/ExportSheetData#32]
Expand the 'Replace existing file' toggle to be a dropdown with the following options:

- Don't Replace (Don't delete or replace any files)
- Trash (Trash existing files with the same name in the same folder)
- Rewrite (Similar to trash, but the most recent file with the same name will have its contents replaced with the newly exported data)

**Comment by Synthoid** [comment]
This can all be done without extra options. The 'Replace existing file' toggle should probably just trash all files with the same name in the export folder after replacing the contents of the most recent file with the shared name.

**Comment by axaneco** [comment]
Would it be possible to implement the "rewrite" option, e.g. the most recent file with the same name will have its contents replaced with the newly exported data? That would result in (if I am right) the same download link for the updated xml export. So, once I have generated a download link for the xml file and the xml would be updated, the link would remain valid for the updated version.

Thanks for the good work!

**Comment by Synthoid** [comment]
That's exactly the idea for the revised feature. It should make sharing links to XML or JSON files much more reliable. I'm going to be busy for the next few weeks, but I'll see if I can get something put together for this soon. Sorry for the delay!

**Comment by axaneco** [comment]
No problem. Looking forward to see this feature whenever it's ready. Thank you for your effort in implementing this add-on.

**Comment by axaneco** [comment]
Thanks for implementation of this feature, now I can access my exported XMLs with a fixed URL. Makes things much more easy for my "Family Infoscreen" project :-)

**Comment by Synthoid** [comment]
This is implemented as of v54.

Glad to hear you are enjoying the feature!
