### ISSUE TITLE
(General) Save your last export settings

### ISSUE THREAD

**Issue by comefouques** [Synthoid/ExportSheetData#34]
When you use ExportSheetData every day on various document, you end up applying always the same settings several time in a day. If the sidebar could memorize your last settings, it would be much easier to keep the same export formatting every time.

In fact, it works as long as you stay on the same document. But as soon as you open a new spreadsheet, your sidebar come back to the default settings.

Something store in your google drive settings ?

**Comment by Synthoid** [comment]
This is the next step for saving/loading export settings after the initial roll out of the feature in V39. Currently, the settings are saved and loaded per document, but there is no way to transfer those settings between sheets. Based on the way settings are stored, I'd prefer to always default to basic settings in new documents, while allowing users to import templates that they have set up. It would also be nice to allow a base template to be set up in place of the default settings.

I think I may be able to do this, so long as I can get the interface for templates to be displayed in an intuitive way. Both this and the [automation workflow](https://github.com/Synthoid/ExportSheetData/issues/9) are likely going to have their own menus, distinct from the sidebar.

**Comment by Synthoid** [comment]
Took a look at initial implementation of systems like this while developing Nested Elements. Unfortunately, it seems like properties (add-on version of preferences) are locked to individual documents. Not an impossible problem, but I will have to think more on how to approach this. Best likely solution currently is a JSON file with setting preferences in it somewhere in your Drive folder, but that is far from ideal.

**Comment by adamreisnz** [comment]
Any update on this issue? I hate having to configure the same settings over and over for each export. Always make a mistake and lose a 5 minutes of time on it.

**Comment by Synthoid** [comment]
Sorry for the extremely delayed response. I haven’t been able to come up with a great solution for this yet. I don’t particularly like having a text file that we read from at a hard set path, and as I noted before, add-on preferences are per document. I could probably allow users to export a blob of JSON settings that can be pasted into another document for setup, but that process would be a little clunky. I apologize that there hasn’t been much progress on this issue due to the lack of a clear path forward.

**Comment by Synthoid** [comment]
Importing/Exporting settings now has its own UI and should be implemented once v65 releases.

![image](https://user-images.githubusercontent.com/6645950/103465997-cd0d1680-4d0e-11eb-93c1-7b8809930e9e.png)
