### ISSUE TITLE
Invalid JSON format when enabling "Ignore empty cells" option

### ISSUE THREAD

**Issue by cstoquer** [Synthoid/ExportSheetData#35]
When exporting a JSON file with the "Ignore empty cells" option enabled, if a cell in the last row is empty, then I can get a comma just before a closing brace, which is incorrect JSON formatting and make my NodeJS process fail when I try to do a `JSON.parse` on it.

Here an example of the data I get (comment added by me to point to the problematic comma)
```js
{
  "test" : [
    {
      "name" : "tacoMan",
      "text" : "hello", // <---- HERE
    },
    {
      "name" : "tacoMan",
      "text" : "Oh, is that a taco... for me?",
      "answers" : [
        "taco:yes, it is for you",
        "notaco: no way!"
      ]
    }
  ]
}
```

**Comment by Synthoid** [comment]
This issue is known and is already tagged [here](https://github.com/Synthoid/ExportSheetData/issues/23). I'm closing this issue since it is a duplicate.
