### ISSUE TITLE
Only last line is exported in JSON

### ISSUE THREAD

**Issue by sailgrib** [Synthoid/ExportSheetData#49]
Hi,

When trying to export data in JSON, only the last is actually exported.
I have tried on multiple Google Sheets with the same result.
I have left all the default parameters and I am exporting only the Current sheet.

Henri

**Comment by Synthoid** [comment]
You don't have Nested Elements enabled? This issue sounds like an output using nested elements without using proper key syntax.

Would you be able to link to an example sheet?

**Comment by Synthoid** [comment]
Closing this issue as it seems to be the expected behavior when Nested Elements is enabled with incorrect key formatting.
