### ISSUE TITLE
Infinite compiling ?

### ISSUE THREAD

**Issue by elTRexx** [Synthoid/ExportSheetData#53]
Hi, I try to have this Json 
```
{
  "MarieCurie": {
    "Win": [
      {"FR": "Super !!",
      "US": "Great !!!"},
      {"FR": "Bravo",
      "US": "Wonderfull"}
    ],
    "Lose": [
      "FR": "Nul !",
      "US": "You sux !"
    ]
  }
}
```
from this simple google sheet : https://docs.google.com/spreadsheets/d/1f8jilee_U0nh1DvsD2jXdeLskFjgdEEeOALDdAFqIcA/edit?usp=sharing

![capture d ecran 2](https://user-images.githubusercontent.com/36304768/36035708-fe6705c2-0db7-11e8-93b8-dc7acbf58ccd.png)

But When I try to export or visualise the Json, I get infinite compile window (like in screenshot).

It is happening when I use the {#ROW} in key formatting.

**Comment by Synthoid** [comment]
Well an infinite compile loop is never fun. Are there any errors in your web console?

**Comment by elTRexx** [comment]
I created a new google sheet, and it works on it ! Strange...

Here is the error of the console web on my (corruped?) original google sheet 👍 
![capture d ecran 3](https://user-images.githubusercontent.com/36304768/36036959-9b737b2c-0dbb-11e8-97f8-1250156251d1.png)

**Comment by elTRexx** [comment]
with expanded error log : 
![capture d ecran 4](https://user-images.githubusercontent.com/36304768/36037060-e5b985b4-0dbb-11e8-9c58-a0f1a4e63fac.png)

**Comment by Synthoid** [comment]
Interesting... Wonder if the add-on was just installed oddly for that sheet? In any case, the new sheet works and is exporting your data as expected?

**Comment by elTRexx** [comment]
Yep

**Comment by Synthoid** [comment]
Hmm, well for now I'll mark the issue as closed and I'll look into why the original sheet didn't export properly. Thanks for posting some screens of your console to help debug the issue!
