### ISSUE TITLE
(JSON) Rows missing when first column contains the same values

### ISSUE THREAD

**Issue by adamreisnz** [Synthoid/ExportSheetData#56]
E.g.

```
first, last
foo, bar
foo, baz
foo, test
```

Export to JSON with setting:

![image](https://user-images.githubusercontent.com/490562/36706179-969b2490-1bcd-11e8-91c0-da2b72111ab8.png)

Expected output is:

```json
[
 {
  "first": "foo",
  "last": "bar"
 },
 {
  "first": "foo",
  "last": "baz"
 },
 {
  "first": "foo",
  "last": "test"
 },
]
```

Actual output is:

```json
[
 {
  "first": "foo",
  "last": "test"
 },
]
```

**Comment by Synthoid** [comment]
Do you have nested elements enabled?

**Comment by adamreisnz** [comment]
No, I used default settings with exporting contents as array.

**Comment by Synthoid** [comment]
Ah, misunderstood the issue. I'm seeing the issue and know what it is. Need to change how contents as array functions. Thanks for finding the issue!

**Comment by adamreisnz** [comment]
No worries, thanks for looking into it.

**Comment by Synthoid** [comment]
Sorry for the delayed response. I know what the actual issue is, but I can only fix this issue for single sheet exports (exporting with "Current sheet only" selected in the "Format" section). This is because the actual output isn't wrong per say, just not what might be expected.

Do you require that your JSON be exported as a raw array, or can you export with "Export sheet arrays" enabled instead?

**Comment by adamreisnz** [comment]
I'm fine with exporting current sheet only, I can merge the arrays of multiple sheets manually later.

What are sheet arrays? An array per sheet? That should be fine too, it would require only minimal work from our end. As long as a single sheet doesn't omit rows due to duplicate values that'd be great.

**Comment by Synthoid** [comment]
[Export sheet arrays](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/exportsheetarrays.md) will export each sheet as an array with individual rows creating the array's elements. This will not have issues with same name fields. Let me know if that works!

**Comment by adamreisnz** [comment]
Ok will give it a try. Can you still fix single sheet export though? It's easy to miss rows this way.

**Comment by AmirSimantov** [comment]
A workaround trick: 

If you do **not** care from the json object name - what this add-on puts before the array, then:

1. Add a dummy column to be the first one (most left). 
2. Put unique strings inside, like a list of incremented numbers (1, 2, 3, etc. Here is how to do it: https://productforums.google.com/forum/#!topic/docs/739M7H2aApE)
3. When reading the json object - ignore its name.
4.

**Comment by Synthoid** [comment]
Sorry this took so long. Should be fixed and shipped in V 46, though only for single sheets as it's functioning as expected for multiple sheets.
