### ISSUE TITLE
Escape special HTML characters when visualizing instead of showing warning

### ISSUE THREAD

**Issue by tomyam1** [Synthoid/ExportSheetData#60]
When visualizing JSON there a warning message about escaped characters:
```
Note: Escaped characters may not display properly when visualized, but will be properly formatted in the exported data.
```
A better approach would be to just escape the special HTML characters before passing them to the  `textarea`, i.e.

```
& => &amp;
> => &gt;
< => &lt;
```

References:
https://stackoverflow.com/a/4037287/1705056
https://stackoverflow.com/a/2502462/1705056

Will you consider a PR for this?

Thanks for this great tool, it says me lots and lots of time!

**Comment by Synthoid** [comment]
Closing this for now. If anyone would like to discuss it more or comes up with some more ideas, feel free to post and we can reopen the issue.

**Comment by tomyam1** [comment]
Hey @Synthoid . Sorry for not responding earlier. I'll make sure to be responsive now.

I didn't quite understand your comment.

a. When exporting the text you gave, both the preview and opening the actual exported file give the same results.
![image](https://user-images.githubusercontent.com/3265649/39116174-69c14bb2-46ec-11e8-84c8-6c9c2d994c78.png)
![image](https://user-images.githubusercontent.com/3265649/39116118-4221f304-46ec-11e8-979c-ade40c702c1b.png)

b. When visualizing/exporting the following sheet:

![image](https://user-images.githubusercontent.com/3265649/39116521-5b34552a-46ed-11e8-8d04-af39b32a6980.png)

You get:

![image](https://user-images.githubusercontent.com/3265649/39116552-6ffdb438-46ed-11e8-9fc4-78c1042aaf3c.png)

![image](https://user-images.githubusercontent.com/3265649/39116623-971b67b8-46ed-11e8-91d7-4b3eaac6123f.png)

If you escape the JSON as I suggested to:

```
{
  "Sheet2": [
    {
      "&amp;lt;&amp;nbsp;&amp;gt;": "&lt;/textarea&gt;"
    }
  ]
}
```

and set the text in the textarea to it, you get the correct result:

![image](https://user-images.githubusercontent.com/3265649/39116769-ecee71ee-46ed-11e8-9edb-0f14364308af.png)

I don't see any downside to that.

**Comment by Synthoid** [comment]
Ah, I see what you're getting at! That absolutely makes sense. I thought you meant convert all JSON escaped characters to HTML escaped chars. This does complicate things though. Currently, the visualized text is the same text as the exported data. This change would require exporting data then converting that data to HTML escaped chars for the display area, correct?

**Comment by Synthoid** [comment]
The warning under the text area is still needed for JSON escaped characters, but your fixes should prevent weird HTML issues now. Thanks!

**Comment by tomyam1** [comment]
Thanks a lot @Synthoid !
(Also for the link you mentioned to testing g suit scripts. If I'll make another PR I'll make sure to read it first)
