### ISSUE TITLE
Add a minify feature to export the data

### ISSUE THREAD

**Issue by thiagolr** [Synthoid/ExportSheetData#63]
I would like to be able to export the data without any spaces in order to decrease the final data size!

**Comment by Synthoid** [comment]
This is something I've had planned for a while now but haven't gotten around to yet. Eventual goal is to allow users to entirely control the white space in exported data. (Tabs, x number of spaces, etc)

**Comment by Synthoid** [comment]
Just pushed v50 of ESD which includes a "Minify JSON" option in the advanced JSON section to do this.
