### ISSUE TITLE
How to get plain array?

### ISSUE THREAD

**Issue by OnkelTem** [Synthoid/ExportSheetData#67]
Hi!

Given a sheet like this:

```
England
Scotland
United Kingdom
Northern Ireland
France
Wales
...
```

I want to get just a simple json like this:

```
[
  "England",
  "Scotland",
  "United Kingdom",
  "Northern Ireland",
  "France",
  "Wales",
  ...
]
```
I have "Export contents as array" switched on but this is what this addon actually returns:

```
[
  {
    "England": "Scotland"
  },
  {
    "England": "United Kingdom"
  },
  {
    "England": "Northern Ireland"
  },
  {
    "England": "France"
  },
  {
    "England": "Wales"
  },
  ...
]
```

How to configure it to not doing what it's not asked?

**Comment by Synthoid** [comment]
Hmm, I think you want to just enable the "[Export value arrays](https://github.com/Synthoid/ExportSheetData/blob/master/docs/json/exportvaluearrays.md)" option. That should do what you want.

**Comment by OnkelTem** [comment]
Thank you very much @Synthoid, it worked!
