### ISSUE TITLE
Nothing is shown in the sidebar

### ISSUE THREAD

**Issue by YImashiro** [Synthoid/ExportSheetData#70]
I added on ExportSheetData to my new google account but nothing is shown in the sidebar 
though I can use it in the other account in which I added it on a few months ago.

**Comment by Synthoid** [comment]
Hmm. I think this is an issue with having multiple accounts signed in. I haven't been able to reproduce the issue on my end, but a few people have noted this issue. I believe it has something to do with how Google handles plugins when multiple people are signed in at once. 

One way around it is to sign out of other accounts. That should let you access everything as expected.
