### ISSUE TITLE
(XML) cannot have a cell value with < or >  

### ISSUE THREAD

**Issue by phtsang** [Synthoid/ExportSheetData#83]
Great work! This is the most promising thing for XML outputs!

I have some values inside my cells as `<` and/or `>`
But the XML output is `&lt;`   and `&gt;`

If this is fixed then I have a working nested XML for my purposes. By using `=CONCATENATE(<child1>,child1,</child1>,<child2>,child2,</child2>)` ?

Thanks!

**Comment by Synthoid** [comment]
By default, illegal XML characters are formatted to use safe encoding. You can disable this by using the [Don't format illegal characters](https://github.com/Synthoid/ExportSheetData/blob/master/docs/xml/dontformatillegalcharacters.md) option. That should do what you want.
