### ISSUE TITLE
JSON Delete same words

### ISSUE THREAD

**Issue by David-Grass-Feria** [Synthoid/ExportSheetData#84]
Hello sir. Thanks for your amazing plugin.
When i create a json file, it will delete same words and use only one. You can see in the image which i send. This **Main Section** table have 17 rows. JSON give me only 9. I think it because, the same words "Title","Comp"..... Can i fix this`?
![gitup-json](https://user-images.githubusercontent.com/16128069/54723632-713cc200-4b68-11e9-9d71-e9f0ee767289.jpg)

**Comment by Synthoid** [comment]
JSON doesn’t support multiple fields with the same name in the same object. I would move the duplicate fields to new rows then export a sheet array. That should export your data intact.

**Comment by derwolf13** [comment]
Okay thanks sir. I think the best way is, i will buy your standard product
first. If works, then i can update to full version.
1 Question: In which folder export your plugin the json file?

Am Samstag, 23. März 2019 schrieb Chris <notifications@github.com>:

**Comment by Synthoid** [comment]
Export Sheet Data is totally free. There is no trial or standard version. You have full access to its feature set by installing it.

The exported JSON file will be in the same folder as the original spreadsheet. If you do not have access to that folder on Drive, the file will instead be placed in your root Drive folder.

**Comment by derwolf13** [comment]
Ahh sorry sir, you are from gitup :) I think it wars a other support for
the plugin  **hehe**
I fix that, i made a space before and it works.
I have a other question: All fields are „input type name“. Can i change
some fields with „ input type file“ ? Maby with a code before..

Am Samstag, 23. März 2019 schrieb Chris <notifications@github.com>:

**Comment by Synthoid** [comment]
You should be able to just rename the field to “file” instead of “name” and reexport the data.

If you want some rows to have a “name” field and others to have a “file” field, you can have two fields named “name” and “file” and enable the “Ignore empty cells” option. Then just populate the appropriate fields in each row. The empty cells will not be included in the exported data for each row.

**Comment by derwolf13** [comment]
Chris, you are great :) I will test next day.
In the future i would like automated export.
If it possible, you create a script for that and i will pay for this. Let
me know :)

Am Samstag, 23. März 2019 schrieb Chris <notifications@github.com>:
