### ISSUE TITLE
Sidebar is empty

### ISSUE THREAD

**Issue by michalutko** [Synthoid/ExportSheetData#96]
I love the plugin and I became reliant on it for my workflow. I noticed today that if I open the sidebar it shows up blank. This hasn't happened before. Please help.
I used Chrome, Safari and Firefox to see if that would resolve the issue. I also tried on forms from different drives and locations with no resolution.
<img width="328" alt="Screen Shot 2019-10-24 at 2 31 54 PM" src="https://user-images.githubusercontent.com/9289256/67527309-91d37a00-f66b-11e9-8d82-d0d5b2c4f365.png">

**Comment by Synthoid** [comment]
Do you have multiple accounts signed in? If so, can you sign out of all but one?

**Comment by dom4op** [comment]
I had the same issue. Can confirm that signing out of all accounts resolves it.

Thanks, Synthoid!

**Comment by Synthoid** [comment]
Glad that resolved the issue for you. Marking this closed for now as that is usually the best way to fix this issue.

I really wish I knew why having multiple accounts signed in causes problems, but as far as I can tell it's a Google API issue so there's not much I can do to fix it anyways.
