### ISSUE TITLE
Visualize/Export buttons don't work.

### ISSUE THREAD

**Issue by extralivesx99** [Synthoid/ExportSheetData#98]
Whenever I press the "Visualize" or "Export" nothing seems to happen. No files created and no popup for visualization. I've used this on other sheets before without issue.

**Comment by Synthoid** [comment]
Hmm. Does the "Compiling JSON/XML..." modal pop up? Do you own the document? Are multiple google accounts signed in?

This could be a few things, so some more info about settings you are using and the doc itself should help hunt down what is going wrong.

**Comment by extralivesx99** [comment]
Hey, so compiling never pops up. It works totally fine in firefox but not
in chrome. I own the document and it's shared to my team.

**Comment by Synthoid** [comment]
Do you have multiple google accounts signed into the browser? Also, just to check, are you using a G suite account?

**Comment by Synthoid** [comment]
Closing this issue as I am assuming it was an issue related to multiple accounts signed in.

**Comment by zzzantzzz** [comment]
I belive this is a cache issue.

I can also confirm this was not working as expected in Chrome. Worked in my personal google account, but not my work one.
Didn't ever load the Settings, and nothing happened when pressing visualize or export.
I own the doc and no one else is signed in.

Works in Microsoft Edge, I assume it works in Firefox as reported.

Cleared the cache in Chrome and now works as expected.

You may want to look into this?

Thanks for the Extension/plugin!
